# docker-compose.yml
version: '3.8' # Specify compose file version

services:
  # Flask Web Application Service
  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: fuzzy_prompts_web
    command: gunicorn --bind 0.0.0.0:8000 "fuzzy_prompts:create_app()" --workers 1 --threads 4 --timeout 120 --access-logfile - --error-logfile - # Command to run Flask app
    volumes:
      - .:/app # Mount current directory to /app in container (good for development)
    ports:
      - "8021:8000" # Map host port 8021 to container port 8000
    environment:
      # Keep Flask/DB/Secret variables
      - FLASK_APP=fuzzy_prompts:create_app
      - FLASK_DEBUG=1 # Set appropriately
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}

      # --- MODIFIED Celery Broker URL ---
      # Directly substitute from .env, using 'guest' as default if var is unset in .env
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672//

      # Keep DB variables if needed elsewhere (e.g., result backend)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db # If your app uses this directly

      # Keep Celery Result Backend if needed
      - CELERY_RESULT_BACKEND=db+postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    env_file:
      - .env     # Load variables from .env file
    networks:
      - fuzzy_prompts_network

  # Celery Worker Service
  worker:
    build: .
    container_name: fuzzy_prompts_worker
    command: >
      bash -c "cd /app && 
      export PYTHONPATH=/app && 
      celery -A celery_app worker --loglevel=DEBUG --concurrency=1 --logfile=/dev/stdout"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=fuzzy_prompts:create_app
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672//
      - CELERY_RESULT_BACKEND=db+postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fuzzy_prompts_network

  # PostgreSQL Database Service
  db:
    image: postgres:15 # Use an official PostgreSQL image (choose version)
    container_name: fuzzy_prompts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist data using a named volume
    environment:
      # Set PostgreSQL user, password, db name - MUST MATCH .env values used by Flask/Celery
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432" # Optional: Map host port if you need direct DB access from host
    healthcheck: # Optional: basic healthcheck
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - fuzzy_prompts_network

  # RabbitMQ Broker Service
  broker:
    image: rabbitmq:3-management
    container_name: fuzzy_prompts_broker
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    user: rabbitmq  # Ensure RabbitMQ runs as the correct user
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fuzzy_prompts_network

networks:
  fuzzy_prompts_network:
    driver: bridge

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence
  rabbitmq_data: # Named volume for RabbitMQ data persistence