"""Add run_serially flag to TestRun

Revision ID: 021c034a59ea
Revises: ba822e5f8765
Create Date: 2025-04-24 14:50:02.872536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021c034a59ea'
down_revision = 'ba822e5f8765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_serially', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_column('run_serially')

    # ### end Alembic commands ###
