"""Added new invalid_characters field to Endpoints

Revision ID: 146a2d6c144e
Revises: 716fdc2e30f6
Create Date: 2025-04-14 12:48:21.307012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146a2d6c144e'
down_revision = '716fdc2e30f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalid_characters', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('invalid_characters')

    # ### end Alembic commands ###
