"""Description

Revision ID: 16bb8d3266ea
Revises: 2453db4f1295
Create Date: 2025-06-05 20:45:38.508372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bb8d3266ea'
down_revision = '2453db4f1295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=10), nullable=False, server_default='POST'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('method')

    # ### end Alembic commands ###
