"""Added transformations to TesttRun

Revision ID: 1a435e6f09a4
Revises: 1e7a3aa0c86c
Create Date: 2025-02-17 11:00:30.291385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a435e6f09a4'
down_revision = '1e7a3aa0c86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_column('transformations')

    # ### end Alembic commands ###
