"""Removed attack from Test Suites model

Revision ID: 279485393e71
Revises: 65d33f113b0d
Create Date: 2025-02-02 16:49:07.395110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279485393e71'
down_revision = '65d33f113b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_column('attack')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attack', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
