"""Removed invalid_characters from endpoint model and instead created a separate PromptFilter model

Revision ID: 59c3be7ab642
Revises: 146a2d6c144e
Create Date: 2025-04-15 13:24:18.230373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c3be7ab642'
down_revision = '146a2d6c144e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('invalid_characters', sa.String(), nullable=True),
    sa.Column('words_to_replace', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_run_filters',
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('prompt_filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_filter_id'], ['prompt_filters.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('test_run_id', 'prompt_filter_id', name='pk_test_run_filters')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('invalid_characters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalid_characters', sa.VARCHAR(), nullable=True))

    op.drop_table('test_run_filters')
    op.drop_table('prompt_filters')
    # ### end Alembic commands ###
