"""Added fields to testcase

Revision ID: 716fdc2e30f6
Revises: 7e5c0520a63d
Create Date: 2025-04-14 11:12:09.382236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '716fdc2e30f6'
down_revision = '7e5c0520a63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('headers')

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('reviewed')

    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sqlite.JSON(), nullable=True))

    op.drop_table('endpoint_headers')
    # ### end Alembic commands ###
