"""Removed APIHeader table and consolidated headers into the endpoints table

Revision ID: 7e5c0520a63d
Revises: 87e7f83ab767
Create Date: 2025-04-10 12:49:31.978740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5c0520a63d'
down_revision = '87e7f83ab767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoint_headers')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_column('headers')

    op.create_table('endpoint_headers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
