"""Added columns to test_cases table

Revision ID: 87e7f83ab767
Revises: 9e63a4e3c890
Create Date: 2025-04-08 13:03:37.350420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e7f83ab767'
down_revision = '9e63a4e3c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attack_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nist_risk', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('nist_risk')
        batch_op.drop_column('data_type')
        batch_op.drop_column('attack_type')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
