"""Added target to dialogue entries

Revision ID: 8da6edba5a22
Revises: 1fe45e6ca432
Create Date: 2025-04-05 23:56:35.288792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da6edba5a22'
down_revision = '1fe45e6ca432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.drop_column('target')

    # ### end Alembic commands ###
