"""Changed transformations to be stored with test suites and not test runs

Revision ID: 9d45676c3a2d
Revises: 1a435e6f09a4
Create Date: 2025-03-03 14:48:36.891335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9d45676c3a2d'
down_revision = '1a435e6f09a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_column('transformations')

    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_column('transformations')

    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformations', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
