"""Init2

Revision ID: a9651929ffa9
Revises: d710b327d9e3
Create Date: 2025-05-13 22:16:50.374256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9651929ffa9'
down_revision = 'd710b327d9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_taskmeta')
    op.drop_table('celery_tasksetmeta')
    with op.batch_alter_table('test_executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_execution_run_attempt_id', type_='foreignkey')
        batch_op.drop_constraint('test_executions_test_case_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_test_execution_run_attempt_id', 'test_run_attempts', ['test_run_attempt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('test_run_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_run_attempt_test_run_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_test_run_attempt_test_run_id', 'test_runs', ['test_run_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_run_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_run_attempt_test_run_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_test_run_attempt_test_run_id', 'test_runs', ['test_run_id'], ['id'])

    with op.batch_alter_table('test_executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_execution_run_attempt_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_executions_test_case_id_fkey', 'test_cases', ['test_case_id'], ['id'])
        batch_op.create_foreign_key('fk_test_execution_run_attempt_id', 'test_run_attempts', ['test_run_attempt_id'], ['id'])

    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_tasksetmeta_pkey'),
    sa.UniqueConstraint('taskset_id', name='celery_tasksetmeta_taskset_id_key')
    )
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_taskmeta_pkey'),
    sa.UniqueConstraint('task_id', name='celery_taskmeta_task_id_key')
    )
    # ### end Alembic commands ###
