"""Added ManualTestRecord table

Revision ID: acf81727b975
Revises: 59c3be7ab642
Create Date: 2025-04-16 19:20:15.112535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf81727b975'
down_revision = '59c3be7ab642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_test_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('payload_sent', sa.Text(), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_test_records')
    # ### end Alembic commands ###
