"""Added objectives to test suites

Revision ID: b43d478a902d
Revises: 741346b65855
Create Date: 2025-03-09 19:02:19.040850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43d478a902d'
down_revision = '741346b65855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_column('objective')

    # ### end Alembic commands ###
