"""Changed cred_encrypted to text

Revision ID: e93a88426b5e
Revises: ef7a0314d3a4
Create Date: 2025-06-15 21:06:52.075186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93a88426b5e'
down_revision = 'ef7a0314d3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('credentials_encrypted',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.alter_column('credentials_encrypted',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
