"""Redundant migrate

Revision ID: f3c06fa39cae
Revises: 9d45676c3a2d
Create Date: 2025-03-03 15:33:38.931579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f3c06fa39cae'
down_revision = '9d45676c3a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformations', sa.JSON(), nullable=True))

    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_column('transformations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transformations', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('transformations')

    # ### end Alembic commands ###
